config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  root 'chats#index'
  resources :users do
    resources :chats, only: [:index, :show, :create]
  end
  resources :sessions, only:[:new, :destroy, :create] 
  resources :messages, only:[:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :users, through: :subscriptions

  validates :identifier, presence: true, uniqueness: true, case_sensitive: false
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :messages, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :chats, through: :subscriptions

  def existing_chats_users
    existing_chat_users = []
    self.chats.each do |chat|
      existing_chat_users.concat(chat.subscriptions.where.not(user_id: self.id).map {|subscription| subscription.user})
    end
    existing_chat_users.uniq
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include UsersHelper
end

app/controllers/chats_controller.rb
require 'securerandom'

class ChatsController < ApplicationController
  before_action :require_login

  def index
    chats = current_user.chats
    @existing_chats_users = current_user.existing_chats_users
  end

  def create
    @other_user = User.find(params[:other_user])
    @chat = find_chat(@other_user) || Chat.new(identifier: SecureRandom.hex)
    if !@chat.persisted?
      @chat.save
      @chat.subscriptions.create(user_id: current_user.id)
      @chat.subscriptions.create(user_id: @other_user.id)
    end
    redirect_to user_chat_path(current_user, @chat, :other_user => @other_user.id)
  end

  def show
    @other_user = User.find(params[:other_user])
    @chat = Chat.find(params[:id])
    @message = Message.new
  end

  private

    def find_chat(second_user)
      chats = current_user.chats 
      chats.each do |chat|
        chat.subscriptions.each do |s|
          if s.user_id == second_user.id
            return chat
          end
        end
      end
      nil
    end

    def require_login
      redirect_to new_session_path unless logged_in?
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    message = Message.new(message_params)
    message.user = current_user

    if message.save
      #broadcasting out to messages channel including the chat_id so messages are broadcasted to specific chat only
      ActionCable.server.broadcast( "messages_#{message_params[:chat_id]}",
        #message and user hold the data we render on the page using javascript 
        message: message.content,
        user: message.user.username)
    else
      redirect_to chats_path
    end
  end

  private
    def message_params
      params.require(:message).permit(:content, :chat_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    unless logged_in?
      @user = User.new
    end
  end

  def create
    @user = User.find_by(username: login_params[:username])
    
    if @user&.authenticate(login_params[:password])
      session[:user_id] = @user.id
      redirect_to users_path
    else 
      flash.now[:notice] = 'Invalid username or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def login_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to users_path
    else 
      render :new
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    @cached_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user != nil
  end
end

app/views/chats/index.html.erb
<ul>
  <% if @existing_chats_users.size != 0 %>
   <% @existing_chats_users.each do |other_user| %>
    <% if other_user != current_user %>
      <li>
        <%= link_to other_user.username, user_chats_path(current_user, :other_user => other_user.id), method: :post %>
      </li>
     <% end %>
   <% end %>
  <% else %>
    <p>No chats yet</p>
  <% end %>
</ul>

All Users:
<ul>
  <% User.all.each do |other_user| %>
   <% if other_user != current_user %>
     <li>
       <%= link_to(user_chats_path(current_user, :other_user => other_user.id), method: :post) do %>
       <%= other_user.username %>
       <% end %>
     </li>
    <% end %>
  <% end %>
</ul>
<%= link_to "Logout", session_path(current_user.id), method: :delete  %>

app/views/chats/show.html.erb
<div>
  <h3>Chat with <%= @other_user.username %></h3>
  <% if @chat.messages.any? %>
    <div id="messages">
      <%= render partial: 'messages/message', collection: @chat.messages.order(id: :asc)%>
    </div>
  <%else%>
    <div id="messages">
    </div>
  <%end%>
</div>
<%= render partial: 'messages/message_form', locals: {message: @message, chat: @chat}%>
</div>
<script>
  createMessageChannel();
  // app/assets/javascripts/channels/messages.js 
  messageForm();
  // app/assets/javascripts/messages_form.js
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chaty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <nav><%= link_to 'Log out', session_path(current_user.id), method: :delete %></nav>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div>
  <p><b><%= message.user.username.capitalize %></b>: <%=message.content%></p>
</div>

app/views/messages/_message_form.html.erb
<%=form_for message, remote: true, authenticity_token: true do |f|%>
  <%= f.text_area :content, data: {textarea: "message"}%>
<!-- this hidden field is for the MessagesController and Action Cable to keep track of what chat this message belongs to -->
<%= f.hidden_field :chat_id, value: chat.id %>
<%end%>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>